### ISSUE TITLE
sanitize fields for android key and keystore passwords

### ISSUE THREAD

**Issue by blackjid** [bitrise-community/steps-generate-cordova-build-configuration#7]
What do you think about sanitizing the passwords in the step log??

https://github.com/bitrise-community/steps-generate-cordova-build-configuration/blob/047eb7987d21aa9ddc4b4e6de3d8618197c7a50a/main.go#L65

https://github.com/bitrise-community/steps-generate-cordova-build-configuration/blob/047eb7987d21aa9ddc4b4e6de3d8618197c7a50a/main.go#L218

**Comment by viktorbenei** [comment]
Good question @blackjid 

We already discussed this a bit internally but will bring it up again. The main reason we print the values there is mainly for debugging as based on the support tickets we received typos in passwords and similar are quite a frequent issue unfortunately.

What do you think about an additional option for the step? Something like "Don't print sensitive configs", which would be turned off by default so that during the configuration it's easier to debug issues, but once it works you could turn it on and remove the values from the logs?

**Comment by viktorbenei** [comment]
In any case we'd be open to something like what I described above (an option to hide these debug infos); if anyone would have some time to send us a PR we'd be happy to review it ;)

**Comment by blackjid** [comment]
hey sorry for the radio silence...  That sounds great...

What do you think going the other way around? Adding a "Debug" option which is turn off by default... and when turned off, all extra info is printed??  For me sound more logical that way, but I understand if that doesn't really cut it for solving your support problem.... let me know... I might be able to get a PR for this :)

**Comment by viktorbenei** [comment]
We'll discuss it with the team, but I'd rather go with the opt-out (debug on by default) behaviour simply because we have to provide user support and it helps a lot to see which configs are actually / correctly provided and which ones are not (if any).
